DROP TYPE IF EXISTS relation_type;
DROP TYPE IF EXISTS entities_relation_type;

DROP TABLE IF EXISTS relation CASCADE;
DROP TABLE IF EXISTS sentence CASCADE;
DROP TABLE IF EXISTS entity CASCADE;
DROP TABLE IF EXISTS entities_relation_type CASCADE;
